name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master, release ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies
        run: |
          pipenv sync
      - name: Lint with flake8
        # NOTE: flake8 については vscode の拡張機能で利用している程度であり、
        #       まだどんなオプションがよさそうか、は検討していません。でも max-line-length が必須なのは知ってる。
        run: |
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pipenv run pytest
